name: Docker Image CI

on:
  push:
    branches:
      - "new-working"
  pull_request:
    branches:
      - "new-working"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag amal99/future-pro:$(date +%s)

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/future-pro
